# Generated by Django 5.0.1 on 2024-01-18 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=100)),
                ('precio', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sede', models.CharField(max_length=100)),
                ('domicilio', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Suscriptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('alta', models.DateField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gimnasio.plan')),
                ('sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gimnasio.sede')),
            ],
        ),
        migrations.CreateModel(
            name='SuscriptoPorSede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gimnasio.sede')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gimnasio.suscriptor')),
            ],
        ),
        migrations.CreateModel(
            name='SuscriptoPorPLan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gimnasio.plan')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gimnasio.suscriptor')),
            ],
        ),
    ]
