# Generated by Django 5.0.1 on 2024-01-18 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gimnasio', '0002_alter_plan_options_alter_suscriptoporplan_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sede',
            old_name='sede',
            new_name='nombre',
        ),
    ]
