# Generated by Django 5.0.1 on 2024-01-18 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gimnasio', '0003_rename_sede_sede_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='plan',
            new_name='nombre',
        ),
    ]
